name: "CodSpeed Performance Analysis"
description: "Continuous benchmarking and performance checks"
branding:
  color: orange
  icon: activity

author: "Arthur Pastel"
inputs:
  token:
    description: "CodSpeed upload token"
    required: false
  run:
    description: "The command to run the benchmarks"
    required: true

  working-directory:
    description: |
      The directory where the `run` command will be executed.
      Warning: if you use defaults.working-directory, you must still set this parameter.
    required: false
  upload-url:
    description: "The upload endpoint (for on-premise deployments)"
    required: false

  runner-version:
    description: "The version of the runner to use"
    required: false

  instruments:
    description: |
      Comma separated list of instruments to enable. The following instruments are available:
      - `mongodb`: MongoDB instrumentation, requires the MongoDB instrument to be enabled for the organization in CodSpeed
    required: false
  mongo-uri-env-name:
    description: |
      The name of the environment variable containing the MongoDB URI. Requires the `mongodb` instrument to be activated in `instruments`.
      If the instrumentation is enabled and this value is not set, the user will need to dynamically provide the MongoDB URI to the CodSpeed runner.
    required: false

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Configure and run codspeed-runner

        # Report that a new version is available
        echo "::warning title=CodSpeed Action Update::A new version v3 is available at https://github.com/CodSpeedHQ/action/releases . You're currently using version v2. Please update to the latest version for improved features and bug fixes."

        if [ -n "${{ inputs.runner-version }}" ]; then
          RUNNER_VERSION="${{ inputs.runner-version }}"
        else
          RUNNER_VERSION=$(cat $GITHUB_ACTION_PATH/.codspeed-runner-version)
        fi

        # Get the runner arguments
        RUNNER_ARGS=""
        if [ -n "${{ inputs.token }}" ]; then
          RUNNER_ARGS="$RUNNER_ARGS --token ${{ inputs.token }}"
        fi
        if [ -n "${{ inputs.working-directory }}" ]; then
          RUNNER_ARGS="$RUNNER_ARGS --working-directory=${{ inputs.working-directory }}"
        fi
        if [ -n "${{ inputs.upload-url }}" ]; then
          RUNNER_ARGS="$RUNNER_ARGS --upload-url=${{ inputs.upload-url }}"
        fi
        if [ -n "${{ inputs.instruments }}" ]; then
          RUNNER_ARGS="$RUNNER_ARGS --instruments=${{ inputs.instruments }}"
        fi
        if [ -n "${{ inputs.mongo-uri-env-name }}" ]; then
          RUNNER_ARGS="$RUNNER_ARGS --mongo-uri-env-name=${{ inputs.mongo-uri-env-name }}"
        fi

        # Install the CodSpeedHQ/runner
        head_status=$(curl -I -fsSL -w "%{http_code}" -o /dev/null https://github.com/CodSpeedHQ/runner/releases/download/v$RUNNER_VERSION/codspeed-runner-installer.sh)
        if [ "$head_status" -eq 404 ]; then
          echo "Error: Version $RUNNER_VERSION is not available in https://github.com/CodSpeedHQ/runner/releases, please a correct version."
          exit 1
        else
          curl -fsSL https://github.com/CodSpeedHQ/runner/releases/download/v$RUNNER_VERSION/codspeed-runner-installer.sh | bash -s -- --quiet
        fi

        # Run the benchmarks
        codspeed-runner $RUNNER_ARGS -- '${{ inputs.run }}'
