name: "CodSpeed Performance Analysis"
description: "Continuous benchmarking and performance checks"
branding:
  color: orange
  icon: activity

author: "Arthur Pastel"
inputs:
  token:
    description: "CodSpeed upload token"
    required: false
  run:
    description: "The command to run the benchmarks"
    required: true

  working-directory:
    description: |
      The directory where the `run` command will be executed.
      Warning: if you use defaults.working-directory, you must still set this parameter.
    required: false
  upload-url:
    description: "The upload endpoint (for on-premise deployments)"
    required: false

  runner-version:
    description: "The version of the runner to use"
    default: "2.0.3"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # Configure and run codspeed-runner

        # Get the runner arguments
        RUNNER_ARGS=""
        if [ -n "${{ inputs.token }}" ]; then
          RUNNER_ARGS="$RUNNER_ARGS --token ${{ inputs.token }}"
        fi
        if [ -n "${{ inputs.working-directory }}" ]; then
          RUNNER_ARGS="$RUNNER_ARGS --working-directory=${{ inputs.working-directory }}"
        fi
        if [ -n "${{ inputs.upload-url }}" ]; then
          RUNNER_ARGS="$RUNNER_ARGS --upload-url=${{ inputs.upload-url }}"
        fi

        # Install the CodSpeedHQ/runner
        head_status=$(curl -I -fsSL -w "%{http_code}" -o /dev/null https://github.com/CodSpeedHQ/runner/releases/download/v${{ inputs.runner-version }}/codspeed-runner-installer.sh)
        if [ "$head_status" -eq 404 ]; then
          echo "Error: Version ${{ inputs.runner-version }} is not available in https://github.com/CodSpeedHQ/runner/releases, please a correct version."
          exit 1
        else
          curl -fsSL https://github.com/CodSpeedHQ/runner/releases/download/v${{ inputs.runner-version }}/codspeed-runner-installer.sh | bash -s -- --quiet
        fi

        # Run the benchmarks
        codspeed-runner $RUNNER_ARGS -- '${{ inputs.run }}'
