name: "CodSpeed Performance Analysis"
description: "Continuous benchmarking and performance checks"
branding:
  color: orange
  icon: activity

author: "Arthur Pastel"
inputs:
  token:
    description: "CodSpeed upload token"
    required: false
  run:
    description: "The command to run the benchmarks"
    required: true
  working-directory:
    description: |
      The directory where the `run` command will be executed.
      Warning: if you use defaults.working-directory, you must still set this parameter.
    required: false

  no-sudo:
    description: "Do not use sudo to setup the environment"
    required: false
  no-pip-install:
    # This will be removed and made the default behavior in the next release
    # https://github.com/CodSpeedHQ/action/issues/83
    description: "Do not install pip dependencies"
    required: false

  upload_url:
    description: "The upload endpoint (for on-premise deployments)"
    default: "https://api.codspeed.io/upload"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
